# Generated by Django 6.0.1 on 2026-02-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["name"],
                "verbose_name": "Participant (Legacy)",
                "verbose_name_plural": "Participants (Legacy)",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registered Participants",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="old_participants",
                to="events.event",
                verbose_name="Registered Events",
            ),
        ),
    ]
