# Generated by Django 6.0.1 on 2026-02-12 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_participant_options_event_participants_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="events/default.jpg",
                null=True,
                upload_to="events/",
                verbose_name="Event Image",
            ),
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RSVP",
                "verbose_name_plural": "RSVPs",
                "unique_together": {("user", "event")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="rsvps",
            field=models.ManyToManyField(
                blank=True,
                related_name="rsvp_events",
                through="events.RSVP",
                to=settings.AUTH_USER_MODEL,
                verbose_name="RSVPs",
            ),
        ),
    ]
