# Generated by Django 6.0.1 on 2026-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_rsvp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                null=True,
                upload_to="events/",
                verbose_name="Event Image",
            ),
        ),
    ]
