# Generated by Django 6.0.1 on 2026-02-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
